version: '3'
services:
   database:
      build: ./db
      ports:
        - "3308:3306"
      env_file: 
        - ./db/secret.env  
      restart: always
   spring:
      build: ./app
      ports:
         - "8089:8080"
      restart: always
   
   
